server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: aero
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
#    url: jdbc:mysql://localhost:3306/dronedb
#    username: root
#    password: root
    url: jdbc:h2:mem:dronedb
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql



logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
